using Ardalis.GuardClauses;
using MIC.Core.Domain.Abstractions;

namespace MIC.Core.Domain.Entities;

/// <summary>
/// Represents a critical intelligence alert generated by the system for operational awareness
/// </summary>
public class IntelligenceAlert : BaseEntity
{
    /// <summary>
    /// Gets the name of the alert
    /// </summary>
    public string AlertName { get; private set; }
    
    /// <summary>
    /// Gets the detailed description of the alert
    /// </summary>
    public string Description { get; private set; }
    
    /// <summary>
    /// Gets the severity level of the alert
    /// </summary>
    public AlertSeverity Severity { get; private set; }
    
    /// <summary>
    /// Gets the current status of the alert
    /// </summary>
    public AlertStatus Status { get; private set; }
    
    /// <summary>
    /// Gets the source system or component that generated the alert
    /// </summary>
    public string Source { get; private set; }
    
    /// <summary>
    /// Gets the timestamp when the alert was triggered
    /// </summary>
    public DateTime TriggeredAt { get; private set; }
    
    /// <summary>
    /// Gets the timestamp when the alert was acknowledged
    /// </summary>
    public DateTime? AcknowledgedAt { get; private set; }
    
    /// <summary>
    /// Gets the user who acknowledged the alert
    /// </summary>
    public string? AcknowledgedBy { get; private set; }
    
    /// <summary>
    /// Gets the timestamp when the alert was resolved
    /// </summary>
    public DateTime? ResolvedAt { get; private set; }
    
    /// <summary>
    /// Gets the user who resolved the alert
    /// </summary>
    public string? ResolvedBy { get; private set; }
    
    /// <summary>
    /// Gets the contextual data associated with the alert
    /// </summary>
    public Dictionary<string, object> Context { get; private set; }
    
    private IntelligenceAlert() 
    { 
        // EF Core constructor - initialize required collections
        AlertName = string.Empty;
        Description = string.Empty;
        Source = string.Empty;
        Context = new Dictionary<string, object>();
    }

    /// <summary>
    /// Creates a new intelligence alert
    /// </summary>
    /// <param name="alertName">The name of the alert</param>
    /// <param name="description">Detailed description</param>
    /// <param name="severity">Severity level</param>
    /// <param name="source">Source system</param>
    public IntelligenceAlert(
        string alertName,
        string description,
        AlertSeverity severity,
        string source)
    {
        AlertName = Guard.Against.NullOrWhiteSpace(alertName, nameof(alertName));
        Description = Guard.Against.NullOrWhiteSpace(description, nameof(description));
        Severity = severity;
        Source = Guard.Against.NullOrWhiteSpace(source, nameof(source));
        Status = AlertStatus.Active;
        TriggeredAt = DateTime.UtcNow;
        Context = new Dictionary<string, object>();
    }

    /// <summary>
    /// Acknowledges the alert
    /// </summary>
    /// <param name="acknowledgedBy">User acknowledging the alert</param>
    public void Acknowledge(string acknowledgedBy)
    {
        Guard.Against.NullOrWhiteSpace(acknowledgedBy, nameof(acknowledgedBy));
        
        if (Status == AlertStatus.Resolved)
            throw new InvalidOperationException("Cannot acknowledge a resolved alert");
            
        Status = AlertStatus.Acknowledged;
        AcknowledgedAt = DateTime.UtcNow;
        AcknowledgedBy = acknowledgedBy;
        MarkAsModified(acknowledgedBy);
        
        AddDomainEvent(new AlertAcknowledgedEvent(Id, AlertName, acknowledgedBy));
    }

    /// <summary>
    /// Resolves the alert
    /// </summary>
    /// <param name="resolvedBy">User resolving the alert</param>
    /// <param name="resolution">Resolution details</param>
    public void Resolve(string resolvedBy, string resolution)
    {
        Guard.Against.NullOrWhiteSpace(resolvedBy, nameof(resolvedBy));
        Guard.Against.NullOrWhiteSpace(resolution, nameof(resolution));
        
        Status = AlertStatus.Resolved;
        ResolvedAt = DateTime.UtcNow;
        ResolvedBy = resolvedBy;
        Context["Resolution"] = resolution;
        MarkAsModified(resolvedBy);
        
        AddDomainEvent(new AlertResolvedEvent(Id, AlertName, resolvedBy));
    }

    /// <summary>
    /// Updates the metadata of the alert
    /// </summary>
    /// <param name="alertName">Updated alert name</param>
    /// <param name="description">Updated description</param>
    /// <param name="severity">Updated severity</param>
    /// <param name="source">Updated source</param>
    /// <param name="updatedBy">User performing the update</param>
    public void UpdateMetadata(
        string alertName,
        string description,
        AlertSeverity severity,
        string source,
        string updatedBy)
    {
        Guard.Against.NullOrWhiteSpace(alertName, nameof(alertName));
        Guard.Against.NullOrWhiteSpace(description, nameof(description));
        Guard.Against.NullOrWhiteSpace(source, nameof(source));
        Guard.Against.NullOrWhiteSpace(updatedBy, nameof(updatedBy));
        
        AlertName = alertName;
        Description = description;
        Severity = severity;
        Source = source;
        MarkAsModified(updatedBy);
        
        AddContextData("LastMetadataUpdate", DateTime.UtcNow);
        AddContextData("LastMetadataUpdateBy", updatedBy);
        
        AddDomainEvent(new AlertMetadataUpdatedEvent(Id, AlertName, updatedBy));
    }

    /// <summary>
    /// Adds contextual data to the alert
    /// </summary>
    public void AddContextData(string key, object value)
    {
        Guard.Against.NullOrWhiteSpace(key, nameof(key));
        Guard.Against.Null(value, nameof(value));
        
        Context[key] = value;
    }
}

/// <summary>
/// Severity levels for intelligence alerts
/// </summary>
public enum AlertSeverity
{
    /// <summary>Informational alert</summary>
    Info = 0,
    /// <summary>Warning level alert</summary>
    Warning = 1,
    /// <summary>Critical issue requiring attention</summary>
    Critical = 2,
    /// <summary>Emergency requiring immediate action</summary>
    Emergency = 3
}

/// <summary>
/// Status of an intelligence alert
/// </summary>
public enum AlertStatus
{
    /// <summary>Alert is active and unacknowledged</summary>
    Active = 0,
    /// <summary>Alert has been acknowledged</summary>
    Acknowledged = 1,
    /// <summary>Alert has been resolved</summary>
    Resolved = 2,
    /// <summary>Alert has been escalated</summary>
    Escalated = 3
}

/// <summary>
/// Domain event raised when an alert is acknowledged
/// </summary>
public record AlertAcknowledgedEvent(Guid AlertId, string AlertName, string AcknowledgedBy) : IDomainEvent
{
    public DateTime OccurredAt { get; } = DateTime.UtcNow;
}

/// <summary>
/// Domain event raised when an alert is resolved
/// </summary>
public record AlertResolvedEvent(Guid AlertId, string AlertName, string ResolvedBy) : IDomainEvent
{
    public DateTime OccurredAt { get; } = DateTime.UtcNow;
}

/// <summary>
/// Domain event raised when an alert's metadata is updated
/// </summary>
public record AlertMetadataUpdatedEvent(Guid AlertId, string AlertName, string UpdatedBy) : IDomainEvent
{
    public DateTime OccurredAt { get; } = DateTime.UtcNow;
}