using System;
using System.Collections.ObjectModel;
using System.Reactive;
using System.Reactive.Linq;
using System.Threading.Tasks;
using MIC.Infrastructure.AI.Services;
using ReactiveUI;
using Microsoft.Extensions.DependencyInjection;
using MIC.Core.Application.Common.Interfaces;
using MIC.Core.Intelligence;
using System.Linq;
using MIC.Core.Domain.Entities;
using MIC.Desktop.Avalonia.Services;

namespace MIC.Desktop.Avalonia.ViewModels;

/// <summary>
/// ViewModel for the Claude AI-style chat interface.
/// </summary>
public class ChatViewModel : ViewModelBase
{
    private readonly IChatService? _chatService;
    private readonly IKnowledgeBaseService? _knowledgeBaseService;
    private readonly PositionQuestionnaireService? _questionnaireService;
    private readonly string _conversationId;
    private string _userInput = string.Empty;
    private bool _isAITyping;
    private string _statusText = "Online";
    private bool _showSuggestions = true;
    private User? _currentUser;

    public ChatViewModel()
    {
        _conversationId = Guid.NewGuid().ToString();
        Messages = new ObservableCollection<ChatMessageViewModel>();
        SuggestedQuestions = new ObservableCollection<string>
        {
            "Show critical alerts",
            "Revenue trends",
            "Performance summary",
            "Today's insights"
        };

        // Try to get services from DI
        _chatService = Program.ServiceProvider?.GetService(typeof(IChatService)) as IChatService;
        _knowledgeBaseService = Program.ServiceProvider?.GetService(typeof(IKnowledgeBaseService)) as IKnowledgeBaseService;
        _questionnaireService = Program.ServiceProvider?.GetService(typeof(PositionQuestionnaireService)) as PositionQuestionnaireService;
        
        // Get current user
        _currentUser = GetUserSession();

        // Set up commands
        SendMessageCommand = ReactiveCommand.CreateFromTask(
            async () => await SendMessageAsync(),
            this.WhenAnyValue(x => x.CanSend));

        ClearChatCommand = ReactiveCommand.CreateFromTask(async () => await ClearChatAsync());

        UseSuggestionCommand = ReactiveCommand.CreateFromTask<string>(async (s) => await UseSuggestionAsync(s));

        // Add welcome message
        AddWelcomeMessage();
    }

    public ChatViewModel(IChatService chatService) : this()
    {
        _chatService = chatService;
    }

    #region Properties

    public ObservableCollection<ChatMessageViewModel> Messages { get; }
    public ObservableCollection<string> SuggestedQuestions { get; }


    public string UserInput
    {
        get => _userInput;
        set
        {
            this.RaiseAndSetIfChanged(ref _userInput, value);
            this.RaisePropertyChanged(nameof(CanSend));
        }
    }

    public bool IsAITyping
    {
        get => _isAITyping;
        set => this.RaiseAndSetIfChanged(ref _isAITyping, value);
    }

    public string StatusText
    {
        get => _statusText;
        set => this.RaiseAndSetIfChanged(ref _statusText, value);
    }

    public bool ShowSuggestions
    {
        get => _showSuggestions && Messages.Count <= 1;
        set => this.RaiseAndSetIfChanged(ref _showSuggestions, value);
    }

    public bool CanSend => !string.IsNullOrWhiteSpace(UserInput) && !IsAITyping;

    #endregion

    #region Commands

    public ReactiveCommand<Unit, Unit> SendMessageCommand { get; }
    public ReactiveCommand<Unit, Unit> ClearChatCommand { get; }
    public ReactiveCommand<string, Unit> UseSuggestionCommand { get; }

    #endregion

    #region Methods

    private User? GetUserSession()
    {
        // Get current user from session
        var session = UserSessionService.Instance.CurrentSession;
        if (session?.UserId != null)
        {
            // In a real implementation, you would fetch the user from the database
            // For now, we'll return a basic user object
            var user = new User
            {
                Username = session.Username,
                Email = session.Email,
                FullName = session.DisplayName,
                JobPosition = session.Position, // Assuming Position is added to session
                Department = session.Department // Assuming Department is added to session
            };
            // Note: Id is read-only and auto-generated by the base class
            return user;
        }
        return null;
    }

    private void AddWelcomeMessage()
    {
        var welcomeText = "Hello! I'm your AI assistant for Mbarie Intelligence Console. ";
        
        if (_currentUser != null)
        {
            welcomeText += $"I recognize you as {_currentUser.FullName ?? _currentUser.Username}";
            if (!string.IsNullOrEmpty(_currentUser.JobPosition))
            {
                welcomeText += $" in the position of {_currentUser.JobPosition}";
            }
            if (!string.IsNullOrEmpty(_currentUser.Department))
            {
                welcomeText += $" in the {_currentUser.Department} department.";
            }
            welcomeText += " ";
        }
        
        welcomeText += "I can help you analyze metrics, review alerts, search your email history, and provide business insights. What would you like to know?";
        
        Messages.Add(new ChatMessageViewModel
        {
            Content = welcomeText,
            IsUser = false,
            Timestamp = DateTime.Now
        });
    }

    private async Task SendMessageAsync()
    {
        if (string.IsNullOrWhiteSpace(UserInput)) return;

        var userMessage = UserInput.Trim();
        UserInput = string.Empty;

        // Add user message to chat
        var userMessageVm = new ChatMessageViewModel
        {
            Content = userMessage,
            IsUser = true,
            Timestamp = DateTime.Now
        };
        Messages.Add(userMessageVm);

        // Hide suggestions after first message
        this.RaisePropertyChanged(nameof(ShowSuggestions));

        // Show typing indicator
        IsAITyping = true;
        StatusText = "Thinking...";

        try
        {
            if (_chatService == null)
            {
                // Fallback response when AI is not configured
                await Task.Delay(500); // Simulate thinking
                Messages.Add(new ChatMessageViewModel
                {
                    Content = "AI services are not configured. Please add your OpenAI API key to the settings to enable AI chat functionality.",
                    IsUser = false,
                    Timestamp = DateTime.Now
                });
            }
            else
            {
                // Check if the query relates to user's emails or knowledge base
                var aiResponse = await ProcessUserQuery(userMessage);

                Messages.Add(new ChatMessageViewModel
                {
                    Content = aiResponse,
                    IsUser = false,
                    Timestamp = DateTime.Now
                });
            }
        }
        catch (Exception ex)
        {
            Messages.Add(new ChatMessageViewModel
            {
                Content = $"An error occurred: {ex.Message}",
                IsUser = false,
                Timestamp = DateTime.Now
            });
        }
        finally
        {
            IsAITyping = false;
            StatusText = "Online";
        }
    }

    private async Task<string> ProcessUserQuery(string userMessage)
    {
        // First, check if this is a knowledge-based query
        if (_knowledgeBaseService != null && _currentUser != null && _currentUser.Id != Guid.Empty)
{
            // Search knowledge base for relevant information
            var knowledgeResults = await _knowledgeBaseService.SearchAsync(userMessage, _currentUser.Id);
            
            if (knowledgeResults.Any())
            {
                // Format knowledge results to include in AI response
                var knowledgeContext = "Based on your email history and documents:\n";
                foreach (var knowledgeResult in knowledgeResults.Take(3)) // Limit to top 3 results
                {
                    knowledgeContext += $"- {knowledgeResult.Title}: {knowledgeResult.Content.Substring(0, Math.Min(knowledgeResult.Content.Length, 200))}...\n";
                }
                
                // Send message to AI with knowledge context
                var enrichedQuery = $"User query: {userMessage}\n\nRelevant information from user's knowledge base:\n{knowledgeContext}";
                if (_chatService != null)
                {
                    var aiResult = await _chatService.SendMessageAsync(enrichedQuery, _conversationId);
                    
                    if (aiResult.Success)
                    {
                        return aiResult.Response;
                    }
                    else
                    {
                        return $"Sorry, I encountered an error: {aiResult.Error}";
                    }
                }
                else
                {
                    return "AI services are not configured.";
                }
            }
        }
        
        // If no knowledge base results or service not available, proceed with regular AI query
        if (_chatService != null)
        {
            var result = await _chatService.SendMessageAsync(userMessage, _conversationId);

            if (result.Success)
            {
                return result.Response;
            }
            else
            {
                return $"Sorry, I encountered an error: {result.Error}";
            }
        }
        else
        {
            return "AI services are not configured.";
        }
    }

    private async Task ClearChatAsync()
    {
        Messages.Clear();

        if (_chatService != null)
        {
            await _chatService.ClearConversationAsync(_conversationId);
        }

        AddWelcomeMessage();
        this.RaisePropertyChanged(nameof(ShowSuggestions));
    }

    private async Task UseSuggestionAsync(string suggestion)
    {
        UserInput = suggestion;
        await SendMessageAsync();
    }

    #endregion
}

/// <summary>
/// ViewModel for individual chat messages.
/// </summary>
public class ChatMessageViewModel : ViewModelBase
{
    public string Content { get; set; } = string.Empty;
    public bool IsUser { get; set; }
    public DateTime Timestamp { get; set; }

    public string FormattedTime => Timestamp.ToString("HH:mm");
}
